name: Ejecutar pruebas unitarias

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependencias
        run: npm install

      - name: Dar permisos de ejecución a Jest
        run: chmod +x ./node_modules/.bin/jest

      - name: Ejecutar pruebas con Jest
        run: npx jest